services:
  - type: web
    name: akmsmp
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATA_DIR
        value: /var/data
      - key: ADMIN_EMAILS
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        value: "1499610921792962672"
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: MC_PUSH_SECRET
        sync: false
      - key: SHOP_URL
        value: https://akmsmp.onrender.com
      - key: MC_HOST
        value: "148.113.2.185"
      - key: MC_PORT
        value: "25565"
    disk:
      name: akmsmp-data
      mountPath: /var/data
      sizeGB: 1
